%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Input:
%   DT  :   delaunayTriangulation object with N generators
%   U   :   Nx2 double array where each row represents the projection
%           vector for the corresponding generator. Each row is assumed to 
%           have unit norm.
% Output:
%   Q   :   Nx2 double array. Row i are the coordinates of the projection
%           of generator i along direction U(i,:) onto the boundary of the
%           Voronoi cell generated by i. 
%   r   :   Nx1 double column vector. r(i) is the distance beween generator
%           i and the projected point Q(i,:). 
%   E   :   mx3 double array where m is the number of generators in the
%           convex hull of DT. The i-th row of E represents the unbounded
%           edge e which comes in counterclockwise from infinity of the
%           Voronoi cell whose generator is the i-th element of
%           convexHull(DT). Specifically, E(i,1) and E(i,2) are the x and y
%           coordinates of the (finite) vertex of e and E(i,3) is the angle
%           in [-pi,pi] at which e radiates to infinity.

function [Q,r,E] = voronoiProjectToBoundary(DT, U)

arguments
    DT delaunayTriangulation
    U (:,2) double {mustBeCompatible(U,DT)}
end

X = DT.Points;
N = size(X,1);

Q = zeros(N,2);
r = zeros(N,1);

CH = convexHull(DT);
[V,C] = voronoiDiagram(DT);

bounds = [min([V; X],[],1) max([V(2:end,:); X],[],1)];
L = 2*(bounds(3)-bounds(1) + bounds(4)-bounds(2));

[~,X_bd] = freeBoundary(DT);
d = circshift(X_bd,-1,1) - X_bd;
unbd_edge_arg = atan2(d(:,2),d(:,1))-pi/2;
unbd_edge_arg = unbd_edge_arg + 2*pi*(unbd_edge_arg < -pi);

%% Interior generators
IN = setdiff(1:N, CH)';
for l = 1:size(IN,1)          % <-- FIX: was size(IN) without dim arg
    i = IN(l);
    a = atan2(U(i,2),U(i,1));
    rayx = [ X(i,1) X(i,1)+L*cos(a) ];
    rayy = [ X(i,2) X(i,2)+L*sin(a) ];
    c = V(C{IN(l)},:);
    c_close = [c; c(1,:)];
    [xi,yi] = rayPolylineIntersect(rayx,rayy,c_close(:,1),c_close(:,2));
    Q(i,:) = [xi yi];
    r(i) = norm( X(i,:) - [xi yi] );
end

%% Boundary generators
m = size(CH,1)-1;
E = zeros(m,3);

for l = 1:m
    i = CH(l);
    c = V(C{i},:);  
    a = atan2(U(i,2),U(i,1));
    a1 = unbd_edge_arg(l);
    a2 = atan2(c(2,2)-X(i,2), c(2,1)-X(i,1));
    a3 = atan2(c(end,2)-X(i,2), c(end,1)-X(i,1));
    a4 = unbd_edge_arg(1+mod(l-2,m));
    [~,S] = sort([a,a1,a2,a3,a4]);
    S = circshift(S, 1-find(S==1));
    switch S(2)
        case 2
            xi = Inf; yi = Inf;
        case 3
            p = c(2,:);
            d = p-X(i,:);
            b = atan2(d(2),d(1));
            h = atan2(U(i,2),U(i,1));
            t = -norm(d)*sin(h-b)*csc(h-a1);
            xi = p(1) + t*cos(a1);
            yi = p(2) + t*sin(a1);
        case 4
            rayx = [ X(i,1) X(i,1)+L*cos(a) ];
            rayy = [ X(i,2) X(i,2)+L*sin(a) ];
            [xi,yi] = rayPolylineIntersect(rayx,rayy,c(2:end,1),c(2:end,2));
        case 5
            p = c(end,:);
            d = p-X(i,:);
            b = atan2(d(2),d(1));
            h = atan2(U(i,2),U(i,1));
            t = -norm(d)*sin(h-b)*csc(h-a4);
            xi = p(1) + t*cos(a4);
            yi = p(2) + t*sin(a4);
   end
    Q(i,:) = [xi yi];
    r(i) = norm( Q(i,:) - X(i,:) );
    E(l,:) = [ c(2,:) a1 ];
end

end

function mustBeCompatible(U,DT)
    if size(U,1) ~= size(DT.Points,1)
        eid = 'Size:notEqual';
        msg = 'Number of rows of second input must match the number of points in the triangulation.';
        throwAsCaller(MException(eid,msg));
    end
end
